### ISSUE TITLE
Energy Skate Park Main checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/energy-skate-park#1]
## Design
- [x] **Sim folder and design doc created** (Date: 09/08/2017) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Legacy sim docs/info gathered**
  - [x] [Sim suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821) reviewed
  - [x] Unfuddle tickets reviewed ([searching tickets](https://github.com/phetsims/phet-info/blob/master/issue-info/unfuddle-ticket-search.md))
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Add an activity
  - [ ] Sim primer draft
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Post-publication items** 
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources), remove legacy version (signed in as phethelp)
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: //)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can
  be found in babel/autoport). The auto-ported strings should then be deleted from babel/autoport.
- [x] **Development started** (Date: 11/16/18)
- [x] **Sim is "feature complete"** (Date: 7/15/20) 
- [x] **Code review completed** (Date: 7/16/20) (https://github.com/phetsims/energy-skate-park/issues/202) 
- [x] **Pre-publication items** 
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Verify credits
- [x] **Published** (Date: 12/14/20) 
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [ ] **Legacy sim tested for bugs**; issues reported in repo
- [ ] **Dev testing started** (Date: //) 
- [ ] **Dev testing complete** (Date: //) 
- [x] **First RC published** (Date: 09/09/20)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 12/07/20)

**Comment by arouinfar** [comment]
Since development is underway, I went ahead and edited https://github.com/phetsims/energy-skate-park/issues/1#issue-257444103 with the latest version of [sim_port_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/sim_port_checklist.md).

**Comment by jessegreenberg** [comment]
@arouinfar @KatieWoe Energy Skate Park 1.1 has been published. Is there anything else to do for this issue for the original checklist or documentation?

**Comment by KatieWoe** [comment]
@arouinfar does it need to be added to the LoL sheet? That's the only thing that comes to mind.

**Comment by jessegreenberg** [comment]
Also @KatieWoe I wasnt sure about some of the unchecked QA boxes in the list, but some of them may not apply.

**Comment by KatieWoe** [comment]
Dev testing was done. Legacy sim testing doesn't really apply.

**Comment by marlitas** [comment]
This sim was published long ago. I believe this checklist can now be closed.
